FROM mcr.microsoft.com/dotnet/core/sdk:2.2

COPY . /app/
WORKDIR /app/


RUN apt update && \
    apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg
WORKDIR /app
COPY ./src/DynamicSerialization/bin/Debug/netcoreapp2.2/ .

EXPOSE 5002-5003
CMD /bin/bash