#creates a new enviroment for python and django applications using postgresql
#change image=name:tag, database settings as needed
version: '3'
services:
  netapp:
    build:
      context: .
      dockerfile: Dockerfile-dotnet
    image: dotnet:dynamic-serialization
    ports: 
      - 5002:5002
      - 5003:5003
    volumes:
      - .:/app
    stdin_open: true
    tty: true
